name: Build

on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  debug_build:
    runs-on: macos-14
    env:
      CONAN_HOME: ${{ github.workspace }}/.conan
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      # You can test your matrix by printing the current Python version
      - name: install conan
        run: |
          pip install conan
          conan profile detect

      - run: conan install . --build '*'

      - run: |
          find "${CONAN_HOME}" -name 'config.log' | xargs cat
        if: always()


  build_wheels:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    env:
      CONAN_HOME: ${{ github.workspace }}/.conan
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [macos-14, ubuntu-22.04]
        python_version: ["cp310-*", "cp311-*", "cp312-*"]
        include:
          - os: macos-14
            llvm_targets: "AArch64"
            llvm_runtimes: "libcxx"

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          SKBUILD_LLVM_TARGETS_TO_BUILD: ${{ matrix.llvm_targets }}
          SKBUILD_LLVM_ENABLE_RUNTIMES: ${{ matrix.llvm_runtimes }}
          CIBW_BUILD: ${{ matrix.python_version }}

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

      - name: Output debugging logs
        run: |
          find "${CONAN_HOME}" -name 'config.log' | xargs cat
        if: always()
